### ISSUE TITLE
Port current vimperator.org website to gh-pages

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator.github.io#1]
@apheleia if you can help out that would be awesome.

We can probably just rely on github's automatic conversion of markdown files into pages.

You can see the current README.md when you go to `vimperator.github.io`.

**Comment by schemar** [comment]
Great! I will check out some details and then get going :+1:

**Comment by schemar** [comment]
@gkatsev are you sure you want the "hacker" theme? By default, it does not include a main menu to link to the different static pages like Vimperator and Muttator.

**Comment by gkatsev** [comment]
I don't think any of the built-in themes have menus that are created automatically. We'd probably want to add links manually and ultimately, probably not rely on the automatic markdown to jekyll conversion.

Also, I think the hacker theme fits with vimperator :)

**Comment by schemar** [comment]
OK, I will add the links manually to the top of every page then.
However, be aware that there is jekyll specific code in the files, e.g. for creating links and using constants.

Later we could also relatively easily adjust the hacker theme to include a header menu.

But first, let me move all the content. The rest we can do when it is time :)

**Comment by schemar** [comment]
I will copy the "Developer Info", but ultimately that should move into the README of the project in my opinion.

**Comment by gkatsev** [comment]
Yup, should just link there.

**Comment by schemar** [comment]
@gkatsev and @maxauthority: Which requirements do you have to move vimperator.org to GitHub pages?

- Any other Jekyll theme could be used very easily. Any preferences? You could open an issue for that.
- Do you require your logo in the header? If so, we need to find out how to change the theme in that way. Probably _after_ you settled on a theme. You could also open an issue for that.

My original intent was to make it easier for people to request changes to the site, as some info was outdated when I read it. By now, the original vimperator.org page has already diverged by adding links to Vimium, etc. I think it would help to switch as soon as we can so that we won't need to generate the same content in two places simultaneously.

**Comment by maxauthority** [comment]
I fully agree, that doing it faster would avoid some duplication effort (although I am too lazy to often update vimperator.org anyway, so that's actually also a reason I like the effort to move the page to github pages, so also others can make the page feel more alive and build the community).

I didn't do the switch because I really dislike the current theme. And yes, reusing the logo somewhere is like a 95% requirement: If the new theme has the ability to make an ad-hoc logo by using CSS/good fonts, it also be ok, but some kind of logo just gives an identity to a project. Also a possibility is to just reuse the favicon somewhere instead of the "full" vimperator-labs logo.

So yes, finding a theme which fits well for presenting various projects would be the next important step. 
After browsing a bit, I think that would server vimperator very well:

https://github.com/lsav/lsav.github.io

(Or in action: https://lsav.github.io/)

We might make 4 "tabs":
Blog | Projects | (Vimperator labs favicon) | Recommendations | GitHub

(Recommendations being for also promoting other "good" stuff like Vimium or VsVim, etc.)

What do you (and others) think?

**Comment by schemar** [comment]
Great! I think the theme fits vimperator nicely :+1:

I will check out how to add that theme with GitHub pages and add the logo there as well. Once that is done, it should be easy to select any custom theme in the future. I just need to figure out once how to add a custom theme. But I think it's almost as easy as adding the sources in the right directory.
